export const CLUB_LIST_REQUEST = 'CLUB_LIST_REQUEST';
export const CLUB_LIST_SUCCESS = 'CLUB_LIST_SUCCESS';
export const CLUB_LIST_FAIL = 'CLUB_LIST_FAIL';

export const CLUB_INVALID_LIST_REQUEST = 'CLUB_INVALID_LIST_REQUEST';
export const CLUB_INVALID_LIST_SUCCESS = 'CLUB_INVALID_LIST_SUCCESS';
export const CLUB_INVALID_LIST_FAIL = 'CLUB_INVALID_LIST_FAIL';

export const CLUB_DETAILS_REQUEST = 'CLUB_DETAILS_REQUEST';
export const CLUB_DETAILS_SUCCESS = 'CLUB_DETAILS_SUCCESS';
export const CLUB_DETAILS_FAIL = 'CLUB_DETAILS_FAIL';

export const CLUB_POST_REQUEST = 'CLUB_POST_REQUEST';
export const CLUB_POST_SUCCESS = 'CLUB_POST_SUCCESS';
export const CLUB_POST_FAIL = 'CLUB_POST_FAIL';

export const CLUB_VALIDATE_REQUEST = 'CLUB_VALIDATE_REQUEST';
export const CLUB_VALIDATE_SUCCESS = 'CLUB_VALIDATE_SUCCESS';
export const CLUB_VALIDATE_FAIL = 'CLUB_VALIDATE_FAIL';

export const CLUB_DELETE_REQUEST = 'CLUB_DELETE_REQUEST';
export const CLUB_DELETE_SUCCESS = 'CLUB_DELETE_SUCCESS';
export const CLUB_DELETE_FAIL = 'CLUB_DELETE_FAIL';