export const INTERVIEW_LIST_REQUEST = 'INTERVIEW_LIST_REQUEST';
export const INTERVIEW_LIST_SUCCESS = 'INTERVIEW_LIST_SUCCESS';
export const INTERVIEW_LIST_FAIL = 'INTERVIEW_LIST_FAIL';

export const INTERVIEW_POST_REQUEST = 'INTERVIEW_POST_REQUEST';
export const INTERVIEW_POST_SUCCESS = 'INTERVIEW_POST_SUCCESS';
export const INTERVIEW_POST_FAIL = 'INTERVIEW_POST_FAIL';

export const INTERVIEW_REPORT_REQUEST = 'INTERVIEW_REPORT_REQUEST';
export const INTERVIEW_REPORT_SUCCESS = 'INTERVIEW_REPORT_SUCCESS';
export const INTERVIEW_REPORT_FAIL = 'INTERVIEW_REPORT_FAIL';

export const INTERVIEW_VALIDATE_REQUEST = 'INTERVIEW_VALIDATE_REQUEST';
export const INTERVIEW_VALIDATE_SUCCESS = 'INTERVIEW_VALIDATE_SUCCESS';
export const INTERVIEW_VALIDATE_FAIL = 'INTERVIEW_VALIDATE_FAIL';

export const INTERVIEW_DELETE_REQUEST = 'INTERVIEW_DELETE_REQUEST';
export const INTERVIEW_DELETE_SUCCESS = 'INTERVIEW_DELETE_SUCCESS';
export const INTERVIEW_DELETE_FAIL = 'INTERVIEW_DELETE_FAIL';

export const INTERVIEW_REPORTED_LIST_REQUEST = 'INTERVIEW_REPORTED_LIST_REQUEST';
export const INTERVIEW_REPORTED_LIST_SUCCESS = 'INTERVIEW_REPORTED_LIST_SUCCESS';
export const INTERVIEW_REPORTED_LIST_FAIL = 'INTERVIEW_REPORTED_LIST_FAIL';