export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

export const REVIEW_POST_REQUEST = 'REVIEW_POST_REQUEST';
export const REVIEW_POST_SUCCESS = 'REVIEW_POST_SUCCESS';
export const REVIEW_POST_FAIL = 'REVIEW_POST_FAIL';

export const REVIEW_REPORT_REQUEST = 'REVIEW_REPORT_REQUEST';
export const REVIEW_REPORT_SUCCESS = 'REVIEW_REPORT_SUCCESS';
export const REVIEW_REPORT_FAIL = 'REVIEW_REPORT_FAIL';

export const REVIEW_VALIDATE_REQUEST = 'REVIEW_VALIDATE_REQUEST';
export const REVIEW_VALIDATE_SUCCESS = 'REVIEW_VALIDATE_SUCCESS';
export const REVIEW_VALIDATE_FAIL = 'REVIEW_VALIDATE_FAIL';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';

export const REVIEW_REPORTED_LIST_REQUEST = 'REVIEW_REPORTED_LIST_REQUEST';
export const REVIEW_REPORTED_LIST_SUCCESS = 'REVIEW_REPORTED_LIST_SUCCESS';
export const REVIEW_REPORTED_LIST_FAIL = 'REVIEW_REPORTED_LIST_FAIL';