export const SCHOOL_LIST_REQUEST = 'SCHOOL_LIST_REQUEST';
export const SCHOOL_LIST_SUCCESS = 'SCHOOL_LIST_SUCCESS';
export const SCHOOL_LIST_FAIL = 'SCHOOL_LIST_FAIL';

export const SCHOOL_LIST_ALL_REQUEST = 'SCHOOL_LIST_ALL_REQUEST';
export const SCHOOL_LIST_ALL_SUCCESS = 'SCHOOL_LIST_ALL_SUCCESS';
export const SCHOOL_LIST_ALL_FAIL = 'SCHOOL_LIST_ALL_FAIL';

export const SCHOOL_DETAILS_REQUEST = 'SCHOOL_DETAILS_REQUEST';
export const SCHOOL_DETAILS_SUCCESS = 'SCHOOL_DETAILS_SUCCESS';
export const SCHOOL_DETAILS_FAIL = 'SCHOOL_DETAILS_FAIL';

export const SCHOOL_POST_REQUEST = 'SCHOOL_POST_REQUEST';
export const SCHOOL_POST_SUCCESS = 'SCHOOL_POST_SUCCESS';
export const SCHOOL_POST_FAIL = 'SCHOOL_POST_FAIL';

export const SCHOOL_VALIDATE_REQUEST = 'SCHOOL_VALIDATE_REQUEST';
export const SCHOOL_VALIDATE_SUCCESS = 'SCHOOL_VALIDATE_SUCCESS';
export const SCHOOL_VALIDATE_FAIL = 'SCHOOL_VALIDATE_FAIL';

export const SCHOOL_DELETE_REQUEST = 'SCHOOL_DELETE_REQUEST';
export const SCHOOL_DELETE_SUCCESS = 'SCHOOL_DELETE_SUCCESS';
export const SCHOOL_DELETE_FAIL = 'SCHOOL_DELETE_FAIL';